name: Build prebuilt APK

on:
  push:
    branches: 
      - 'A12.1'
    paths-ignore:
      - '**.mkdn'
      - '.**'
  pull_request:
      paths-ignore:
      - '**.mkdn'
      - '.**'
  workflow_dispatch:

jobs:
  build-release-apk:
    runs-on: ubuntu-latest
    continue-on-error: true
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Clone our prebuilts
        run: |
          git clone https://.:${{ secrets.API_TOKEN_GITHUB }}@github.com/Flamingo-OS/vendor_prebuilts
          mkdir app/libs
          cp vendor_prebuilts/libs/framework.jar vendor_prebuilts/libs/support-compose.aar app/libs/

      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11
          
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build release APK
        run: ./gradlew assembleRelease

      - name: Rename artifact
        if: ${{ !github.event.pull_request }}
        run: |
          oldArtifactPath="app/build/outputs/apk/release/app-release-unsigned.apk"
          newArtifactPath="app/build/outputs/apk/release/Updater.apk"
          echo "ARTIFACT_PATH=$newArtifactPath" >> $GITHUB_ENV
          mv "$oldArtifactPath" "$newArtifactPath"

      - name: Setting git config
        if: ${{ !github.event.pull_request }}
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Export commit hash
        if: ${{ !github.event.pull_request }}
        run: |
          git_hash=$(git rev-parse "$GITHUB_SHA")
          link="https://github.com/Flamingo-OS/packages_apps_Updater/commit/$git_hash"
          echo "GIT_LINK=$link" >> $GITHUB_ENV
          
      - name: Uploading artifact
        if: ${{ !github.event.pull_request }}
        run: |
          mkdir -p vendor_prebuilts/app/Updater
          cp ${{ env.ARTIFACT_PATH }} vendor_prebuilts/app/Updater
          cd vendor_prebuilts/
          git pull
          git add .
          git diff-index --quiet HEAD || git commit -m "Update Updater APK for ${{ env.GIT_LINK }}"
          git push origin A12.1
